/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Battle {
  'id' : string,
  'status' : BattleStatus,
  'creator' : Principal,
  'winner' : [] | [Principal],
  'createdTimestamp' : Time,
  'entryFee' : bigint,
  'roomCode' : [] | [string],
  'opponent' : [] | [Principal],
}
export type BattleStatus = { 'Disputed' : null } |
  { 'Open' : null } |
  { 'PendingResult' : null } |
  { 'Active' : null } |
  { 'Completed' : null };
export interface ChatMessage {
  'battleId' : string,
  'text' : string,
  'sender' : Principal,
  'timestamp' : Time,
}
export type ExternalBlob = Uint8Array;
export type Time = bigint;
export interface User {
  'registeredTimestamp' : Time,
  'principal' : Principal,
  'username' : string,
  'mobileNumber' : string,
  'accountNumber' : string,
  'walletBalance' : bigint,
}
export interface UserProfile {
  'registeredTimestamp' : Time,
  'username' : string,
  'mobileNumber' : string,
  'accountNumber' : string,
  'walletBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WalletTransaction {
  'id' : string,
  'status' : WalletTransactionStatus,
  'user' : Principal,
  'notes' : string,
  'timestamp' : Time,
  'txType' : WalletTransactionType,
  'amount' : bigint,
}
export type WalletTransactionStatus = { 'Rejected' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type WalletTransactionType = { 'Deposit' : null } |
  { 'BattleEntry' : null } |
  { 'Withdrawal' : null } |
  { 'BattleWin' : null };
export interface WinnerClaim {
  'battleId' : string,
  'evidenceBlobId' : ExternalBlob,
  'claimant' : Principal,
  'claimedWinner' : Principal,
  'timestamp' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveDeposit' : ActorMethod<[string], undefined>,
  'approveWin' : ActorMethod<[string, Principal], undefined>,
  'approveWithdrawal' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimWin' : ActorMethod<[string, ExternalBlob], undefined>,
  'createBattle' : ActorMethod<[bigint], undefined>,
  'getBattleRoom' : ActorMethod<
    [string],
    { 'messages' : Array<ChatMessage>, 'battle' : Battle }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMe' : ActorMethod<[], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinBattle' : ActorMethod<[string], undefined>,
  'listAllBattles' : ActorMethod<[], Array<Battle>>,
  'listBattles' : ActorMethod<[], Array<Battle>>,
  'listPendingClaims' : ActorMethod<[], Array<WinnerClaim>>,
  'listPendingTransactions' : ActorMethod<[], Array<WalletTransaction>>,
  'register' : ActorMethod<[string, string], undefined>,
  'rejectClaim' : ActorMethod<[string, string], undefined>,
  'rejectWithdrawal' : ActorMethod<[string], undefined>,
  'requestDeposit' : ActorMethod<[bigint, string], undefined>,
  'requestWithdrawal' : ActorMethod<[bigint, string], undefined>,
  'saveAccountNumber' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveMobileNumber' : ActorMethod<[string], undefined>,
  'sendChatMessage' : ActorMethod<[string, string], undefined>,
  'setAdmin' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];