/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'battleId' : IDL.Text,
  'text' : IDL.Text,
  'sender' : IDL.Principal,
  'timestamp' : Time,
});
export const BattleStatus = IDL.Variant({
  'Disputed' : IDL.Null,
  'Open' : IDL.Null,
  'PendingResult' : IDL.Null,
  'Active' : IDL.Null,
  'Completed' : IDL.Null,
});
export const Battle = IDL.Record({
  'id' : IDL.Text,
  'status' : BattleStatus,
  'creator' : IDL.Principal,
  'winner' : IDL.Opt(IDL.Principal),
  'createdTimestamp' : Time,
  'entryFee' : IDL.Nat,
  'roomCode' : IDL.Opt(IDL.Text),
  'opponent' : IDL.Opt(IDL.Principal),
});
export const UserProfile = IDL.Record({
  'registeredTimestamp' : Time,
  'username' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'accountNumber' : IDL.Text,
  'walletBalance' : IDL.Nat,
});
export const User = IDL.Record({
  'registeredTimestamp' : Time,
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'accountNumber' : IDL.Text,
  'walletBalance' : IDL.Nat,
});
export const WinnerClaim = IDL.Record({
  'battleId' : IDL.Text,
  'evidenceBlobId' : ExternalBlob,
  'claimant' : IDL.Principal,
  'claimedWinner' : IDL.Principal,
  'timestamp' : Time,
});
export const WalletTransactionStatus = IDL.Variant({
  'Rejected' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const WalletTransactionType = IDL.Variant({
  'Deposit' : IDL.Null,
  'BattleEntry' : IDL.Null,
  'Withdrawal' : IDL.Null,
  'BattleWin' : IDL.Null,
});
export const WalletTransaction = IDL.Record({
  'id' : IDL.Text,
  'status' : WalletTransactionStatus,
  'user' : IDL.Principal,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'txType' : WalletTransactionType,
  'amount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveDeposit' : IDL.Func([IDL.Text], [], []),
  'approveWin' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'approveWithdrawal' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimWin' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'createBattle' : IDL.Func([IDL.Nat], [], []),
  'getBattleRoom' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'messages' : IDL.Vec(ChatMessage), 'battle' : Battle })],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMe' : IDL.Func([], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinBattle' : IDL.Func([IDL.Text], [], []),
  'listAllBattles' : IDL.Func([], [IDL.Vec(Battle)], []),
  'listBattles' : IDL.Func([], [IDL.Vec(Battle)], ['query']),
  'listPendingClaims' : IDL.Func([], [IDL.Vec(WinnerClaim)], []),
  'listPendingTransactions' : IDL.Func([], [IDL.Vec(WalletTransaction)], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectClaim' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectWithdrawal' : IDL.Func([IDL.Text], [], []),
  'requestDeposit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveAccountNumber' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveMobileNumber' : IDL.Func([IDL.Text], [], []),
  'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setAdmin' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'battleId' : IDL.Text,
    'text' : IDL.Text,
    'sender' : IDL.Principal,
    'timestamp' : Time,
  });
  const BattleStatus = IDL.Variant({
    'Disputed' : IDL.Null,
    'Open' : IDL.Null,
    'PendingResult' : IDL.Null,
    'Active' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const Battle = IDL.Record({
    'id' : IDL.Text,
    'status' : BattleStatus,
    'creator' : IDL.Principal,
    'winner' : IDL.Opt(IDL.Principal),
    'createdTimestamp' : Time,
    'entryFee' : IDL.Nat,
    'roomCode' : IDL.Opt(IDL.Text),
    'opponent' : IDL.Opt(IDL.Principal),
  });
  const UserProfile = IDL.Record({
    'registeredTimestamp' : Time,
    'username' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'accountNumber' : IDL.Text,
    'walletBalance' : IDL.Nat,
  });
  const User = IDL.Record({
    'registeredTimestamp' : Time,
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'accountNumber' : IDL.Text,
    'walletBalance' : IDL.Nat,
  });
  const WinnerClaim = IDL.Record({
    'battleId' : IDL.Text,
    'evidenceBlobId' : ExternalBlob,
    'claimant' : IDL.Principal,
    'claimedWinner' : IDL.Principal,
    'timestamp' : Time,
  });
  const WalletTransactionStatus = IDL.Variant({
    'Rejected' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const WalletTransactionType = IDL.Variant({
    'Deposit' : IDL.Null,
    'BattleEntry' : IDL.Null,
    'Withdrawal' : IDL.Null,
    'BattleWin' : IDL.Null,
  });
  const WalletTransaction = IDL.Record({
    'id' : IDL.Text,
    'status' : WalletTransactionStatus,
    'user' : IDL.Principal,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'txType' : WalletTransactionType,
    'amount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveDeposit' : IDL.Func([IDL.Text], [], []),
    'approveWin' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'approveWithdrawal' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimWin' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'createBattle' : IDL.Func([IDL.Nat], [], []),
    'getBattleRoom' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'messages' : IDL.Vec(ChatMessage), 'battle' : Battle })],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMe' : IDL.Func([], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinBattle' : IDL.Func([IDL.Text], [], []),
    'listAllBattles' : IDL.Func([], [IDL.Vec(Battle)], []),
    'listBattles' : IDL.Func([], [IDL.Vec(Battle)], ['query']),
    'listPendingClaims' : IDL.Func([], [IDL.Vec(WinnerClaim)], []),
    'listPendingTransactions' : IDL.Func([], [IDL.Vec(WalletTransaction)], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectClaim' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectWithdrawal' : IDL.Func([IDL.Text], [], []),
    'requestDeposit' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveAccountNumber' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveMobileNumber' : IDL.Func([IDL.Text], [], []),
    'sendChatMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setAdmin' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };